### ISSUE TITLE
ambiguous implicit values when creating own helpers

### ISSUE THREAD

**Issue by mkurz** [adrianhurt/play-bootstrap3#32]
I am using a Play Java project.

I followed the instructions [here](http://play-bootstrap3.herokuapp.com/extend-it#create-helper) to create my own email helper. I created the **exact same** file `app/views/b3/my/email.scala.html` like you described in the docs.
Running the app gives me:
```
play.sbt.PlayExceptions$CompilationException: Compilation error[ambiguous implicit values:
 both method implicitJavaMessages in object PlayMagicForJava of type => play.api.i18n.Messages
 and value messages of type play.api.i18n.Messages
 match expected type play.api.i18n.Messages]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.6.jar:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.6.jar:na]
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
```

Whats the problem and how to work around? (Likely this only occurs in Java Projects?)

**Comment by adrianhurt** [comment]
Sorry for the delay. I've just tried it and you're right. It seems it only happens with Play 2.4 and Java. I'm now busy but I will find the problem as soon as possible.

**Comment by mkurz** [comment]
I think this happened with Play 2.3 already as well.

**Comment by adrianhurt** [comment]
I've just tested it with [the first Java tutorial](https://www.typesafe.com/activator/template/play-java-intro-reactive-platform-15v01) with Play 2.3 and the last snapshot of _play-bootstrap3_ and it works fine.

For Play 2.4 it seems to work simply removing the implicit `Messages` argument from your custom template. This `Messages` argument will be taken from the `PlayMagicForJava` object.

I'm now thinking about including the `Messages` argument within the `B3FieldConstructor` for the next version in order to have only the `B3FieldConstructor` argument for every helper instead of the pair `B3FieldConstructor-Messages`.

**Comment by mkurz** [comment]
Thanks for your answer,  so I will just remove the `Messages` argument then.
Thanks!

**Comment by adrianhurt** [comment]
I've added a clarification in the docs page
